# Generated by Django 4.0.9 on 2023-02-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='contents',
        ),
    ]
