# Generated by Django 4.0.9 on 2023-02-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_remove_file_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
